# Generated by Django 6.0.5 on 2026-05-25 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_item_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField()),
                ('total_borrowing_events', models.IntegerField(default=0)),
                ('total_units_deployed', models.IntegerField(default=0)),
                ('avg_deployment_duration_days', models.FloatField(default=0.0)),
                ('active_deployments', models.IntegerField(default=0)),
                ('on_time_returns', models.IntegerField(default=0)),
                ('delayed_returns', models.IntegerField(default=0)),
                ('return_rate_percentage', models.FloatField(default=0.0)),
                ('equipment_deployed', models.IntegerField(default=0)),
                ('consumable_deployed', models.IntegerField(default=0)),
                ('medical_deployed', models.IntegerField(default=0)),
                ('safety_deployed', models.IntegerField(default=0)),
                ('tools_deployed', models.IntegerField(default=0)),
                ('most_borrowed_category', models.CharField(max_length=20)),
                ('logistics_efficiency_score', models.FloatField(default=0.0)),
                ('trend', models.CharField(choices=[('INCREASING', 'Increasing Deployment'), ('STABLE', 'Stable Operations'), ('DECREASING', 'Decreasing Deployment')], default='STABLE', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('most_borrowed_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_records', to='core.item')),
            ],
            options={
                'ordering': ['-month_year'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('RESTOCK_ALERT', 'Restock Alert'), ('LOW_STOCK', 'Low Stock Warning'), ('OUT_OF_STOCK', 'Out of Stock'), ('OVERDUE_RETURN', 'Overdue Return'), ('ANALYTICS_UPDATE', 'Analytics Update'), ('SYSTEM', 'System Message')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_required', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical - Out of Stock Risk'), ('HIGH', 'High - Low Stock Warning'), ('MEDIUM', 'Medium - Preventive Restock'), ('LOW', 'Low - Routine Check')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESTOCKED', 'Restocked'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=15)),
                ('current_quantity', models.IntegerField()),
                ('predicted_quantity', models.IntegerField()),
                ('recommended_restock', models.IntegerField()),
                ('predicted_stockout_date', models.DateField(blank=True, null=True)),
                ('avg_weekly_consumption', models.FloatField()),
                ('consumption_trend', models.CharField(choices=[('STABLE', 'Stable'), ('INCREASING', 'Increasing'), ('DECREASING', 'Decreasing')], max_length=20)),
                ('reason', models.TextField()),
                ('alert_generated_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_alerts', to='core.item')),
            ],
            options={
                'ordering': ['-alert_generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('consumable_consumed', models.IntegerField(default=0)),
                ('borrowed_quantity', models.IntegerField(default=0)),
                ('total_movement', models.IntegerField(default=0)),
                ('avg_daily_consumption', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_analytics', to='core.item')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('item', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='SupplyConsumptionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField()),
                ('total_consumed', models.IntegerField(default=0)),
                ('total_borrowed', models.IntegerField(default=0)),
                ('total_restocked', models.IntegerField(default=0)),
                ('restock_count', models.IntegerField(default=0)),
                ('avg_daily_consumption', models.FloatField(default=0.0)),
                ('consumption_variance', models.FloatField(default=0.0)),
                ('peak_consumption_day', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(max_length=20)),
                ('deployment_status', models.CharField(choices=[('STABLE', 'Stable Supply'), ('CRITICAL', 'Critical Consumption'), ('BUILDING', 'Building Reserves'), ('TRANSITIONING', 'Transitioning')], default='STABLE', max_length=50)),
                ('predicted_consumption_next_month', models.FloatField(default=0.0)),
                ('min_restock_recommended', models.IntegerField(default=0)),
                ('optimal_restock_quantity', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_cycles', to='core.item')),
            ],
            options={
                'ordering': ['-month_year'],
                'unique_together': {('item', 'month_year')},
            },
        ),
    ]
