# Generated by Django 6.0.5 on 2026-05-25 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_logisticsanalytics_notification_restockalert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='condition_on_return',
            field=models.TextField(blank=True, help_text='Free-text condition notes on return'),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='inspected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='wear_score',
            field=models.FloatField(blank=True, help_text='0-100 wear/damage score reported on return', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='integrity_score',
            field=models.FloatField(default=100.0, help_text='0-100 integrity score; lower means more worn'),
        ),
        migrations.AddField(
            model_name='item',
            name='last_inspection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lifespan_days',
            field=models.IntegerField(blank=True, help_text='Approx lifespan in days (optional)', null=True),
        ),
        migrations.CreateModel(
            name='MaintenanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical - Replace Now'), ('HIGH', 'High - Replace Soon'), ('MEDIUM', 'Medium - Schedule Maintenance'), ('LOW', 'Low - Monitor')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('MAINTAINED', 'Maintained'), ('REPLACED', 'Replaced'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=15)),
                ('current_integrity', models.FloatField(blank=True, null=True)),
                ('predicted_end_of_life', models.DateField(blank=True, null=True)),
                ('recommended_action', models.CharField(blank=True, max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('alert_generated_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_maintenance_alerts', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_alerts', to='core.item')),
            ],
            options={
                'ordering': ['-alert_generated_at'],
            },
        ),
    ]
