# Generated by Django 6.0.5 on 2026-05-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_borrowing_condition_on_return_borrowing_inspected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='max_capacity',
            field=models.IntegerField(blank=True, help_text='Maximum inventory capacity for this item', null=True),
        ),
    ]
