# Generated by Django 6.0.5 on 2026-05-30 19:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_item_max_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('age', models.IntegerField()),
                ('cellphone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('program_year', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('registration_no', models.CharField(help_text='e.g. BLSHP-24-DOHCaraga-5407', max_length=100, unique=True)),
                ('qr_payload', models.CharField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=20)),
                ('complaints', models.JSONField(blank=True, default=list)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('pulse', models.CharField(blank=True, max_length=50)),
                ('spo2', models.CharField(blank=True, max_length=50)),
                ('respiration_rate', models.CharField(blank=True, max_length=50)),
                ('blood_pressure', models.CharField(blank=True, max_length=50)),
                ('temperature', models.CharField(blank=True, max_length=50)),
                ('dcap_btls', models.JSONField(blank=True, default=list)),
                ('body_assessment', models.JSONField(blank=True, default=list)),
                ('medical_history_checkboxes', models.JSONField(blank=True, default=list)),
                ('signs_symptoms', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('past_medical_history', models.TextField(blank=True)),
                ('last_oral_intake', models.TextField(blank=True)),
                ('events_leading_to_incident', models.TextField(blank=True)),
                ('first_aid_notes', models.TextField(blank=True)),
                ('responder_name', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('signature_data', models.TextField(blank=True)),
                ('date_signed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ResponderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('total_duration_seconds', models.IntegerField(default=0)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.responder')),
            ],
        ),
    ]
